
### Create a new list in blocking way (SLOW)
# @name b-list
POST localhost:8888/b-list

### Create a new list (non blocking)
# @name list

// this creates a new draft after some time
POST localhost:8888/list

### Save a new item in a list
# @name save-list

// copy the ID from created draft and put it here immediately, to experience the queue effect
POST localhost:8888/list/a633aebf-7270-4b43-9f3d-a274e75a3d30/foo

### Query a list
# @name query-list

// eventially you will see the item you saved
GET localhost:8888/list


### Operations status

GET localhost:8888/ops/84c9cd4a-163a-44db-a7f2-2ff4b28d7cbe
