
### Create a new list in blocking way (SLOW)
# @name b-list
POST localhost:8888/b-list

### Create a new list (non blocking)
# @name list

// this creates a new draft after some time
POST localhost:8888/list

### Save a new item in a list
# @name save-list

// copy the ID and put it here immediately, to see the queue effect
POST localhost:8888/list/76ebf6e8-0db8-4bff-ad62-b9bf1c3b72f0/ime

### Query a list
# @name query-list

// eventially you will see the item you saved
GET localhost:8888/list


### Operations status

GET localhost:8888/ops/2925175e-2039-4342-a06d-6b8e6efd3635
